parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: blog
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5f9dbd928b7d2434fba327f7d135fc2f8a0f0660
    database_path: null
